```{r echo = FALSE, results = "hide"}
round = function(x, digits = 0){
floor(x * 10^digits + 0.5) / 10^digits
}
n1    = sample(200:300, 1)
med1  = round(runif(1, 130, 150), 2)
des1  = round(runif(1, 10, 15), 2)
n2    = sample(200:300, 1)
med2  = round(runif(1, 130, 150), 2)
des2  = round(runif(1, 10, 15), 2)
con   = round(runif(1, 80, 99), 2)
alfa  = round(1 - con/100, 4)
li    = round(med1 - med2 - qnorm(1 - alfa/2)*sqrt(des1^2/n1 + des2^2/n2), 2)
ls    = round(med1 - med2 + qnorm(1 - alfa/2)*sqrt(des1^2/n1 + des2^2/n2), 2)
res   = c(li, ls)
```

Question
========
Un equipo de investigadores está estudiando la presión arterial sistólica en dos grupos $A$ y $B$ de pacientes con hipertensión, cuyas desviaciones estándar poblacionales son de $`r des1`$ mmHg y $`r des2`$ mmHg, respectivamente. Un grupo de $`r n1`$ pacientes del grupo $A$ tiene una media de la presión de $`r med1`$ mmHg, mientras que un grupo de $`r n2`$ pacientes del grupo $B$ tiene una media de la presión de $`r med2`$ mmHg. Con base en esta información, determina lo siguiente, redondeando en cada inciso **HASTA EL FINAL** de las operaciones, usando precisión de $2$ decimales.

a) El límite inferior del intervalo del $`r con`\%$ de confianza para la diferencia de las medias $\mu_A -\mu_B$ de la presión arterial sistólica de los pacientes.
b) El límite superior del intervalo del $`r con`\%$ de confianza para la diferencia de las medias $\mu_A -\mu_B$ de la presión arterial sistólica de los pacientes.

Solution
========
De acuerdo con los datos del enunciado:

a) **Límite inferior:**
\begin{align*}
\bar{X}_1 - \bar{X}_2 - z_{1-\alpha/2} \sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}
&= `r med1` - `r med2` - z_{1-\frac{`r alfa`}{2}} \sqrt{\frac{`r des1`^2}{`r n1`} + \frac{`r des2`^2}{`r n2`}}\\
&= `r med1` - `r med2` - \texttt{qnorm}(1 - `r alfa`/2) \times \sqrt{\frac{`r des1`^2}{`r n1`} + \frac{`r des2`^2}{`r n2`}}\\
&= `r li`\ \text{mmHg}
\end{align*}

b) **Límite superior:**
\begin{align*}
\bar{X}_1 - \bar{X}_2 + z_{1-\alpha/2} \sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}
&= `r med1` - `r med2` + z_{1-\frac{`r alfa`}{2}} \sqrt{\frac{`r des1`^2}{`r n1`} + \frac{`r des2`^2}{`r n2`}}\\
&= `r med1` - `r med2` + \texttt{qnorm}(1 - `r alfa`/2) \times \sqrt{\frac{`r des1`^2}{`r n1`} + \frac{`r des2`^2}{`r n2`}}\\
&= `r ls`\ \text{mmHg}
\end{align*}

Meta-information
================
extype: num
exsolution: `r li`|`r ls`
extol: 0.01